
package br.feevale.tc.oee.ws.programacao;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "inserirProgramacaoProducaoEquipamentoService", targetNamespace = "programacao.ws.oee.tc.feevale.br", wsdlLocation = "http://localhost:8080/oee/ws/inserirProgramacaoProducaoEquipamentoServiceDefinition.wsdl")
public class InserirProgramacaoProducaoEquipamentoService
    extends Service
{

    private final static URL INSERIRPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException INSERIRPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_EXCEPTION;
    private final static QName INSERIRPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_QNAME = new QName("programacao.ws.oee.tc.feevale.br", "inserirProgramacaoProducaoEquipamentoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/oee/ws/inserirProgramacaoProducaoEquipamentoServiceDefinition.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSERIRPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_WSDL_LOCATION = url;
        INSERIRPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_EXCEPTION = e;
    }

    public InserirProgramacaoProducaoEquipamentoService() {
        super(__getWsdlLocation(), INSERIRPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_QNAME);
    }

    public InserirProgramacaoProducaoEquipamentoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSERIRPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_QNAME, features);
    }

    public InserirProgramacaoProducaoEquipamentoService(URL wsdlLocation) {
        super(wsdlLocation, INSERIRPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_QNAME);
    }

    public InserirProgramacaoProducaoEquipamentoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSERIRPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_QNAME, features);
    }

    public InserirProgramacaoProducaoEquipamentoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InserirProgramacaoProducaoEquipamentoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InserirProgramacaoProducaoEquipamento
     */
    @WebEndpoint(name = "inserirProgramacaoProducaoEquipamentoSoap11")
    public InserirProgramacaoProducaoEquipamento getInserirProgramacaoProducaoEquipamentoSoap11() {
        return super.getPort(new QName("programacao.ws.oee.tc.feevale.br", "inserirProgramacaoProducaoEquipamentoSoap11"), InserirProgramacaoProducaoEquipamento.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InserirProgramacaoProducaoEquipamento
     */
    @WebEndpoint(name = "inserirProgramacaoProducaoEquipamentoSoap11")
    public InserirProgramacaoProducaoEquipamento getInserirProgramacaoProducaoEquipamentoSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("programacao.ws.oee.tc.feevale.br", "inserirProgramacaoProducaoEquipamentoSoap11"), InserirProgramacaoProducaoEquipamento.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSERIRPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_EXCEPTION!= null) {
            throw INSERIRPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_EXCEPTION;
        }
        return INSERIRPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_WSDL_LOCATION;
    }

}
