
package br.feevale.tc.oee.ws.programacao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "inserirProgramacaoProducaoEquipamento", targetNamespace = "programacao.ws.oee.tc.feevale.br")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InserirProgramacaoProducaoEquipamento {


    /**
     * 
     * @param inserirProgramacaoProducaoEquipamentoRequest
     * @return
     *     returns br.feevale.tc.oee.ws.programacao.InserirProgramacaoProducaoEquipamentoResponse
     */
    @WebMethod
    @WebResult(name = "inserirProgramacaoProducaoEquipamentoResponse", targetNamespace = "programacao.ws.oee.tc.feevale.br", partName = "inserirProgramacaoProducaoEquipamentoResponse")
    public InserirProgramacaoProducaoEquipamentoResponse inserirProgramacaoProducaoEquipamento(
        @WebParam(name = "inserirProgramacaoProducaoEquipamentoRequest", targetNamespace = "programacao.ws.oee.tc.feevale.br", partName = "inserirProgramacaoProducaoEquipamentoRequest")
        InserirProgramacaoProducaoEquipamentoRequest inserirProgramacaoProducaoEquipamentoRequest);

}
